Add generator & move handlebars files into framework folder
fusionalliance/starter-kit pull request #39
Opened 2020-09-03 20:38 UTC by swcolegrove

2020-10-12 23:30 UTC, swcolegrove commented on src/frameworks/handlebars/index.js
> +  this.log('Coyping templates');
im gonna change this so it creates a new directory for the project similar to other framework cli tools

2020-10-16 16:01 UTC, davidragsdale requested changes
Just a few changes

2020-10-16 16:04 UTC, swcolegrove commented on src/frameworks/handlebars/index.js
> +    'watch:html': 'nodemon -e hbs --exec \"npm run build:html\"',
Yep i tested this, if we try to escape the escapes we end up with both escapes still in the destination package.json

2020-10-16 16:04 UTC, swcolegrove commented on src/frameworks/handlebars/index.js
> +  this.log('Coyping common files');
me good at spell

2020-10-16 16:13 UTC, swcolegrove commented on src/util/destinationPath.js
> +module.exports = function destinationPath(folder = '') {
I think leaving it as empty string is fine, it does not always need a folder/file name if you are copying directly into the root folder for instance

2020-10-16 16:15 UTC, davidragsdale approved these changes
LGTM. 🚀

2020-10-19 14:05 UTC, tgardnerFusion approved these changes
Looks gouda 🧀

2020-10-19 14:07 UTC, merged